### ISSUE TITLE
results is not expected

### ISSUE THREAD

**Issue by BlankAix** [GeneralLi95/PyTorch_UCMerced_LandUse#2]
Sorry to disturb.
I've downloaded the code and it runs well. But after 100 epochs even 200 epochs, the accuracy seems always around 50%. So I increase the batch size to 16 or try different optimizer but the best accuracy is 80%.
Could you give me some advice? Really Thanks for you code.

**Comment by GeneralLi95** [comment]
@BlankAix I got you. Maybe you can clear the former model and run it again.  I'm too busy these days for my final year project. I will see whether I can do something if I have some spare time.

**Comment by BlankAix** [comment]
发现你也是中国人，2333。你先忙你自己的事，我这边自己努力调下参数，但如果你不介意的话可以将你跑完的权重上传到项目吗？谢谢回复~祝你顺利毕业。

**Comment by GeneralLi95** [comment]
@BlankAix GitHub 上传下载比较慢，我传个百度云链接给你吧一会，不过好长时间没碰了，我也不知道结果啥样。

**Comment by GeneralLi95** [comment]
@BlankAix 留个邮箱吧，我把 checkpoint 百度云链接发给你

**Comment by BlankAix** [comment]
@GeneralLi95 834833309@qq.com 。十分感谢~

**Comment by rongtongxueya** [comment]
笑死了在这里hhh
